###
POST http://localhost:3000/api/user/register
Content-Type: application/json; charset=utf-8

{
  "name": "Kyle",
  "email": "kyle@pm.me",
  "password": "password"
}

###
POST http://localhost:3000/api/user/login
Content-Type: application/json; charset=utf-8

{
  "email": "kyle@pm.me",
  "password": "password"
}

###
POST http://localhost:3000/api/posts
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE1NWEyZmIyMjE4MzQyMjg4MjYxYzEiLCJpYXQiOjE1OTUyMzU0MzQsImV4cCI6MTU5NTIzNTczNH0.coARSfzXzyTJ2XQMOpW94ypC0_AvjBjtguezs2T2y2dM5rOw2QjkCEvHBGdlgCWTQPLjuAE_JdmuLPuyvIMryg
Content-Type: application/json; charset=utf-8

###
POST http://localhost:3000/notfound
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE1NWEyZmIyMjE4MzQyMjg4MjYxYzEiLCJpYXQiOjE1OTUyMzU0MzQsImV4cCI6MTU5NTIzNTczNH0.coARSfzXzyTJ2XQMOpW94ypC0_AvjBjtguezs2T2y2dM5rOw2QjkCEvHBGdlgCWTQPLjuAE_JdmuLPuyvIMryg
Content-Type: application/json; charset=utf-8
